//! The only module allowed to touch `Python<'py>` / `Bound`.
//!
//! Engine structs store GIL-independent `Py<PyAny>` handles and re-bind
//! them here per GIL session.

use std::path::{Path, PathBuf};

use pyo3::prelude::*;
use pyo3::types::{PyDict, PyList, PyModule};

use crate::collect::{MarkData, TestItem, file_nodeid, module_name_for};
use crate::fixture::{FixtureDef, FixtureRegistry, Scope};

// All embedded Python shim sources (generated by build.rs from py/):
// `pytest` is the public API shim; `_pytest` mirrors the internal module
// paths that upstream test suites import.
include!(concat!(env!("OUT_DIR"), "/shim_manifest.rs"));

/// The per-run directory holding the embedded Python shim packages. Plugin
/// crates write their own importable packages (e.g. pytest_mock) here.
pub fn shim_root() -> PathBuf {
    std::env::temp_dir().join(format!("pytest-rs-{}", std::process::id()))
}

/// An embedded interpreter does not activate a virtualenv on its own: when
/// VIRTUAL_ENV is set, add its site-packages via site.addsitedir — which
/// also processes .pth files (editable installs), unlike PYTHONPATH — and
/// move the added entries to the front so the venv shadows the base env.
pub fn activate_virtualenv(py: Python<'_>) -> PyResult<()> {
    py.run(
        c"
import glob as _glob
import os as _os
import site as _site
import sys as _sys

_venv = _os.environ.get('VIRTUAL_ENV')
if _venv:
    _candidates = _glob.glob(_os.path.join(_venv, 'lib', 'python*', 'site-packages'))
    _candidates.append(_os.path.join(_venv, 'Lib', 'site-packages'))
    for _dir in _candidates:
        if _os.path.isdir(_dir) and _dir not in _sys.path:
            _before = len(_sys.path)
            _site.addsitedir(_dir)
            _added = _sys.path[_before:]
            del _sys.path[_before:]
            _sys.path[:0] = _added
",
        None,
        None,
    )
}

/// Set up the embedded interpreter for a run: write the pytest shim package
/// to a temp dir and prepend it to sys.path so `import pytest` resolves to us.
pub fn install_shim(py: Python<'_>) -> PyResult<PathBuf> {
    let shim_root = shim_root();
    for (rel, content) in SHIM_FILES {
        let path = shim_root.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)
                .map_err(|e| pyo3::exceptions::PyOSError::new_err(e.to_string()))?;
        }
        std::fs::write(&path, content)
            .map_err(|e| pyo3::exceptions::PyOSError::new_err(e.to_string()))?;
    }
    sys_path_prepend(py, &shim_root)?;

    // Expose the Rust-backed request type for `_pytest.fixtures` imports.
    let pytest_module = py.import("pytest")?;
    pytest_module.setattr("FixtureRequest", py.get_type::<crate::request::PyRequest>())?;

    // Assertion rewriting: rewrite `assert` in test modules at import time.
    py.import("pytest._rewrite")?.call_method0("install")?;

    // The embedded interpreter never runs Python's exit machinery, so a
    // block-buffered (piped) stdout would silently drop test prints.
    py.run(
        c"import sys
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(line_buffering=True)
    except (AttributeError, ValueError):
        pass
",
        None,
        None,
    )?;

    // The pytester fixture spawns this binary to run nested sessions.
    if let Ok(exe) = std::env::current_exe() {
        py.import("os")?
            .getattr("environ")?
            .set_item("PYTEST_RS_EXE", exe.to_string_lossy())?;
    }

    // Embedded interpreters inherit argv[0] as sys.executable, which would
    // make `subprocess.run([sys.executable, ...])` re-run pytest-rs
    // recursively. Point it at the real python binary instead.
    py.run(
        c"import os, sys, sysconfig
if not os.path.basename(sys.executable).startswith('python'):
    for _name in ('python' + sysconfig.get_config_var('VERSION'), 'python3'):
        _candidate = os.path.join(sysconfig.get_config_var('BINDIR'), _name)
        if os.path.exists(_candidate):
            sys.executable = _candidate
            break
",
        None,
        None,
    )?;
    Ok(shim_root)
}

/// Register the shim's builtin fixtures (tmp_path, monkeypatch, pytester,
/// doctest_namespace) with global visibility.
pub fn register_builtin_fixtures(py: Python<'_>, registry: &mut FixtureRegistry) -> PyResult<()> {
    let pytest_module = py.import("pytest")?;
    register_fixtures_from(py, &pytest_module, "", registry)?;
    let doctest_module = py.import("_pytest.doctest")?;
    register_fixtures_from(py, &doctest_module, "", registry)?;
    Ok(())
}

/// The 1-based first line of a callable's definition (0 if unknown).
fn first_lineno(py: Python<'_>, func: &Bound<'_, PyAny>) -> u32 {
    let _ = py;
    func.getattr("__code__")
        .and_then(|code| code.getattr("co_firstlineno"))
        .and_then(|line| line.extract::<u32>())
        .unwrap_or(0)
}

/// xunit setup state per module/class: None = setup succeeded; Some(exc) =
/// it raised, and every later test of that scope re-raises the same error
/// (pytest's cached-failure semantics).
#[derive(Default)]
struct XunitState {
    modules: std::collections::HashMap<String, Option<Py<PyAny>>>,
    classes: std::collections::HashMap<String, Option<Py<PyAny>>>,
}

/// The cached setup status for a key: None = never ran, Some(None) = ok,
/// Some(Some(exc)) = failed with exc.
fn xunit_status(
    py: Python<'_>,
    session: &crate::session::Session,
    class_scope: bool,
    key: &str,
) -> Option<Option<Py<PyAny>>> {
    let state = session.stash_get::<XunitState>()?;
    let map = if class_scope {
        &state.classes
    } else {
        &state.modules
    };
    map.get(key)
        .map(|status| status.as_ref().map(|exc| exc.clone_ref(py)))
}

fn xunit_record(
    py: Python<'_>,
    session: &mut crate::session::Session,
    class_scope: bool,
    key: String,
    error: Option<&PyErr>,
) {
    let state = session
        .stash_get_mut::<XunitState>()
        .expect("xunit state inserted");
    let map = if class_scope {
        &mut state.classes
    } else {
        &mut state.modules
    };
    map.insert(
        key,
        error.map(|err| err.value(py).clone().unbind().into_any()),
    );
}

/// xunit-style setup hooks (setup_module / setup_function for plain
/// functions, setup_class / setup_method for Test classes). Teardowns are
/// pushed onto the session finalizer stack at the matching scope, so they
/// drain LIFO with the fixture finalizers (class scope drains when the
/// runner moves to the next class).
pub fn ensure_xunit_setup(
    py: Python<'_>,
    session: &mut crate::session::Session,
    item: &TestItem,
    instance: Option<&Py<PyAny>>,
) -> PyResult<()> {
    // Doctest text file items have no module to import; skip xunit hooks.
    if item.module_name == "__doctest_textfile__" {
        return Ok(());
    }
    let xunit = py.import("pytest._xunit")?;
    let call_optional = xunit.getattr("call_optional")?;
    let bind = xunit.getattr("bind")?;
    let module = py.import(item.module_name.as_str())?;
    let module_instance = item.module_instance();

    if session.stash_get::<XunitState>().is_none() {
        session.stash_insert(XunitState::default());
    }

    match xunit_status(py, session, false, &module_instance) {
        Some(Some(exc)) => {
            // setup_module already failed: every test re-raises that error.
            return Err(PyErr::from_value(exc.bind(py).clone()));
        }
        Some(None) => {}
        None => {
            let setup_result: PyResult<()> = match module.getattr("setup_module") {
                Ok(setup) => call_optional.call1((setup, &module)).map(|_| ()),
                Err(_) => Ok(()),
            };
            if let Err(err) = setup_result {
                xunit_record(py, session, false, module_instance, Some(&err));
                return Err(err);
            }
            xunit_record(py, session, false, module_instance.clone(), None);
            if let Ok(teardown) = module.getattr("teardown_module") {
                let finalizer = bind.call1((teardown, &module))?;
                session.finalizers.push(crate::session::PendingFinalizer {
                    scope: Scope::Module,
                    instance: module_instance.clone(),
                    finalizer: crate::session::Finalizer::Callable(finalizer.unbind()),
                });
            }
        }
    }

    match (&item.cls, instance) {
        (Some(cls), Some(instance)) => {
            let cls = cls.bind(py);
            let class_key = item.class_instance();
            match xunit_status(py, session, true, &class_key) {
                Some(Some(exc)) => {
                    return Err(PyErr::from_value(exc.bind(py).clone()));
                }
                Some(None) => {}
                None => {
                    let setup_result: PyResult<()> = match cls.getattr("setup_class") {
                        Ok(setup) => call_optional.call1((setup, cls)).map(|_| ()),
                        Err(_) => Ok(()),
                    };
                    if let Err(err) = setup_result {
                        xunit_record(py, session, true, class_key, Some(&err));
                        return Err(err);
                    }
                    xunit_record(py, session, true, class_key, None);
                    if let Ok(teardown) = cls.getattr("teardown_class") {
                        let finalizer = bind.call1((teardown, cls))?;
                        session.finalizers.push(crate::session::PendingFinalizer {
                            scope: Scope::Class,
                            instance: item.class_instance(),
                            finalizer: crate::session::Finalizer::Callable(finalizer.unbind()),
                        });
                    }
                }
            }
            let instance = instance.bind(py);
            // pytest passes the *bound* method object to setup/teardown_method.
            let bound_method = instance.getattr(item.func_name.as_str())?;
            if let Ok(setup) = instance.getattr("setup_method") {
                call_optional.call1((setup, &bound_method))?;
            }
            if let Ok(teardown) = instance.getattr("teardown_method") {
                let finalizer = bind.call1((teardown, &bound_method))?;
                session.finalizers.push(crate::session::PendingFinalizer {
                    scope: Scope::Function,
                    instance: item.nodeid.clone(),
                    finalizer: crate::session::Finalizer::Callable(finalizer.unbind()),
                });
            }
        }
        _ => {
            if let Ok(setup) = module.getattr("setup_function") {
                call_optional.call1((setup, item.func.bind(py)))?;
            }
            if let Ok(teardown) = module.getattr("teardown_function") {
                let finalizer = bind.call1((teardown, item.func.bind(py)))?;
                session.finalizers.push(crate::session::PendingFinalizer {
                    scope: Scope::Function,
                    instance: item.nodeid.clone(),
                    finalizer: crate::session::Finalizer::Callable(finalizer.unbind()),
                });
            }
        }
    }
    Ok(())
}

/// Register fixtures defined by a plugin-provided Python module (e.g. the
/// pytest_mock shim) with global visibility.
pub fn register_plugin_fixtures(
    py: Python<'_>,
    module: &Bound<'_, PyModule>,
    registry: &mut FixtureRegistry,
) -> PyResult<()> {
    register_fixtures_from(py, module, "", registry)
}

pub fn sys_path_prepend(py: Python<'_>, path: &Path) -> PyResult<()> {
    let sys_path = py.import("sys")?.getattr("path")?;
    let sys_path = sys_path.cast::<PyList>().map_err(PyErr::from)?;
    let entry = path.to_string_lossy().to_string();
    if !sys_path.contains(&entry)? {
        sys_path.insert(0, entry)?;
    }
    Ok(())
}

/// Names of the fixture-requesting parameters of a Python callable, in
/// order: positional/keyword params without defaults (defaulted params and
/// *args/**kwargs are not fixture requests, matching pytest).
pub fn param_names(py: Python<'_>, func: &Bound<'_, PyAny>) -> PyResult<Vec<String>> {
    let inspect = py.import("inspect")?;
    let signature = inspect.getattr("signature")?.call1((func,))?;
    let parameters = signature.getattr("parameters")?;
    let empty = inspect.getattr("Parameter")?.getattr("empty")?;
    let mut names = Vec::new();
    for value in parameters.call_method0("values")?.try_iter()? {
        let parameter = value?;
        let kind = parameter.getattr("kind")?;
        let kind_name: String = kind.getattr("name")?.extract()?;
        if kind_name != "POSITIONAL_OR_KEYWORD" && kind_name != "KEYWORD_ONLY" {
            continue;
        }
        if !parameter.getattr("default")?.is(&empty) {
            continue;
        }
        names.push(parameter.getattr("name")?.extract()?);
    }
    Ok(names)
}

/// pytest compat.num_mock_patch_args: how many leading parameters are
/// injected by stacked @unittest.mock.patch decorators (their `patchings`
/// entries with no attribute_name and new=DEFAULT). Those are mock-filled
/// positionally at call time, not fixture requests.
pub fn num_mock_patch_args(py: Python<'_>, func: &Bound<'_, PyAny>) -> usize {
    let Ok(patchings) = func.getattr("patchings") else {
        return 0;
    };
    let Ok(iter) = patchings.try_iter() else {
        return 0;
    };
    // Both the stdlib and the rolling-backport `mock` define the sentinel;
    // like pytest, only consult already-imported modules (sys.modules).
    let modules = py
        .import("sys")
        .and_then(|sys| sys.getattr("modules"))
        .ok();
    let sentinels: Vec<Bound<'_, PyAny>> = ["unittest.mock", "mock"]
        .iter()
        .filter_map(|name| {
            modules
                .as_ref()?
                .get_item(name)
                .ok()?
                .getattr("DEFAULT")
                .ok()
        })
        .collect();
    iter.flatten()
        .filter(|p| {
            let no_attribute_name = p
                .getattr("attribute_name")
                .map(|v| !v.is_truthy().unwrap_or(true))
                .unwrap_or(false);
            let new_is_default = p
                .getattr("new")
                .map(|new| sentinels.iter().any(|s| new.is(s)))
                .unwrap_or(false);
            no_attribute_name && new_is_default
        })
        .count()
}

pub struct AsyncFlags {
    pub is_coroutine: bool,
    pub is_generator: bool,
    pub is_async_gen: bool,
}

pub fn async_flags(py: Python<'_>, func: &Bound<'_, PyAny>) -> PyResult<AsyncFlags> {
    let inspect = py.import("inspect")?;
    Ok(AsyncFlags {
        is_coroutine: inspect
            .getattr("iscoroutinefunction")?
            .call1((func,))?
            .extract()?,
        is_generator: inspect
            .getattr("isgeneratorfunction")?
            .call1((func,))?
            .extract()?,
        is_async_gen: inspect
            .getattr("isasyncgenfunction")?
            .call1((func,))?
            .extract()?,
    })
}

/// Import one test module and introspect it: append discovered test items
/// and fixture definitions (objects carrying recorded shim metadata).
pub fn collect_module(
    py: Python<'_>,
    rootdir: &Path,
    path: &Path,
    items: &mut Vec<TestItem>,
    registry: &mut FixtureRegistry,
    hooks: &mut Vec<crate::session::PyHook>,
) -> PyResult<()> {
    let (basedir, module_name) = module_name_for(path);
    sys_path_prepend(py, &basedir)?;
    let module = py.import(module_name.as_str())?;
    let nodeid_base = file_nodeid(rootdir, path);

    register_pytest_plugins(py, &module, registry, hooks)?;
    introspect_namespace(
        py,
        &module,
        &nodeid_base,
        &module_name,
        path,
        items,
        registry,
    )
}

/// Collect doctest items from an already-imported Python module.
/// Returns items appended to `items`; `py_config` is the PyConfig proxy.
pub fn collect_doctests_from_module(
    py: Python<'_>,
    rootdir: &Path,
    path: &Path,
    py_config: &Py<PyAny>,
    items: &mut Vec<TestItem>,
) -> PyResult<()> {
    let (basedir, module_name) = module_name_for(path);
    sys_path_prepend(py, &basedir)?;
    let nodeid_base = file_nodeid(rootdir, path);
    let doctest_mod = py.import("_pytest.doctest")?;
    let results = doctest_mod
        .getattr("collect_module_doctests")?
        .call1((
            module_name.as_str(),
            path.to_string_lossy().as_ref(),
            nodeid_base.as_str(),
            py_config.bind(py),
        ))?;
    for item in results.try_iter()? {
        let tuple = item?;
        let nodeid: String = tuple.get_item(0)?.extract()?;
        let func: Py<PyAny> = tuple.get_item(1)?.extract()?;
        let lineno: u32 = tuple.get_item(2)?.extract()?;
        // Derive func_name from the last "::" component of the nodeid.
        let func_name = nodeid
            .rsplit("::")
            .next()
            .unwrap_or(&nodeid)
            .to_string();
        items.push(TestItem {
            nodeid,
            path: path.to_path_buf(),
            module_name: module_name.clone(),
            func_name,
            func,
            cls: None,
            is_coroutine: false,
            is_doctest: true,
            fixture_names: vec!["doctest_namespace".to_string(), "request".to_string()],
            extra_fixture_names: vec![],
            marks: vec![],
            callspec: vec![],
            fixture_params: vec![],
            lineno,
        });
    }
    Ok(())
}

/// Collect doctest items from a text file (e.g. `*.rst`).
pub fn collect_doctests_from_textfile(
    py: Python<'_>,
    rootdir: &Path,
    path: &Path,
    py_config: &Py<PyAny>,
    items: &mut Vec<TestItem>,
) -> PyResult<()> {
    let nodeid_base = file_nodeid(rootdir, path);
    let doctest_mod = py.import("_pytest.doctest")?;
    let results = doctest_mod
        .getattr("collect_textfile_doctests")?
        .call1((
            path.to_string_lossy().as_ref(),
            nodeid_base.as_str(),
            py_config.bind(py),
        ))?;
    for item in results.try_iter()? {
        let tuple = item?;
        let nodeid: String = tuple.get_item(0)?.extract()?;
        let func: Py<PyAny> = tuple.get_item(1)?.extract()?;
        let lineno: u32 = tuple.get_item(2)?.extract()?;
        let func_name = nodeid
            .rsplit("::")
            .next()
            .unwrap_or(&nodeid)
            .to_string();
        items.push(TestItem {
            nodeid,
            path: path.to_path_buf(),
            module_name: "__doctest_textfile__".to_string(),
            func_name,
            func,
            cls: None,
            is_coroutine: false,
            is_doctest: true,
            fixture_names: vec!["doctest_namespace".to_string(), "request".to_string()],
            extra_fixture_names: vec![],
            marks: vec![],
            callspec: vec![],
            fixture_params: vec![],
            lineno,
        });
    }
    Ok(())
}

/// Check whether a file path matches --doctest-glob patterns.
pub fn is_doctest_textfile(
    py: Python<'_>,
    path: &Path,
    py_config: &Py<PyAny>,
) -> PyResult<bool> {
    let doctest_mod = py.import("_pytest.doctest")?;
    let result = doctest_mod
        .getattr("is_doctest_textfile")?
        .call1((path.to_string_lossy().as_ref(), py_config.bind(py)))?;
    result.extract()
}

/// `pytest_plugins = "name"` / `pytest_plugins = (...)` in a test module:
/// import each named module and register its hooks and fixtures globally.
/// Bundled plugins (pytest_asyncio, ...) resolve to their shims and carry
/// no pytest_* hooks, so importing them here is a no-op.
fn register_pytest_plugins(
    py: Python<'_>,
    module: &Bound<'_, PyModule>,
    registry: &mut FixtureRegistry,
    hooks: &mut Vec<crate::session::PyHook>,
) -> PyResult<()> {
    let Ok(declared) = module.getattr("pytest_plugins") else {
        return Ok(());
    };
    let names: Vec<String> = match declared.extract::<String>() {
        Ok(single) => vec![single],
        Err(_) => declared
            .try_iter()?
            .map(|name| name?.extract::<String>())
            .collect::<PyResult<_>>()?,
    };
    load_named_plugins(py, &names, registry, hooks)
}

/// Import plugin modules by name (`-p NAME` / `pytest_plugins`) and register
/// their fixtures and pytest_* hooks globally.
pub fn load_named_plugins(
    py: Python<'_>,
    names: &[String],
    registry: &mut FixtureRegistry,
    hooks: &mut Vec<crate::session::PyHook>,
) -> PyResult<()> {
    for name in names {
        // Built-in plugin names ("pytester", ...) aren't importable modules;
        // they're provided natively, so only importable plugins register.
        let Ok(plugin) = py.import(name.as_str()) else {
            continue;
        };
        // Re-registering an already-seen plugin would duplicate its hooks.
        let already = hooks
            .iter()
            .any(|hook| hook.plugin_module.as_deref() == Some(name.as_str()));
        if already {
            continue;
        }
        register_fixtures_from(py, &plugin, "", registry)?;
        let before = hooks.len();
        scan_py_hooks(&plugin, "", hooks)?;
        for hook in &mut hooks[before..] {
            hook.plugin_module = Some(name.clone());
        }
    }
    Ok(())
}

/// Distributions whose pytest11 plugin must not autoload under the shim:
/// the bundled set (pytest-rs replaces them natively) plus plugins known
/// to require real pytest internals at hook time. hypothesis works fully
/// as a library without its plugin (which only adds reporting/CLI
/// integration but calls pytest.Function & co. from its hooks).
const SKIPPED_DISTS: [&str; 7] = [
    "pytest-asyncio",
    "pytest-mock",
    "pytest-cov",
    "pytest-split",
    "pytest-benchmark",
    "pytest-xdist",
    "hypothesis",
];

/// Auto-load installed third-party plugins (`pytest11` entry points),
/// pytest's setuptools-plugin loading. `blocked` carries `-p no:NAME`
/// names (matched against the entry-point name and its module);
/// PYTEST_DISABLE_PLUGIN_AUTOLOAD disables the pass entirely. Unlike
/// pytest, a plugin that fails to import warns (PytestConfigWarning) and
/// is skipped instead of aborting the run: plugins built against real
/// pytest internals would otherwise make every run unusable.
pub fn load_entrypoint_plugins(
    py: Python<'_>,
    blocked: &[String],
    registry: &mut FixtureRegistry,
    hooks: &mut Vec<crate::session::PyHook>,
) -> PyResult<()> {
    if std::env::var_os("PYTEST_DISABLE_PLUGIN_AUTOLOAD").is_some() {
        return Ok(());
    }
    let globals = pyo3::types::PyDict::new(py);
    globals.set_item("bundled", SKIPPED_DISTS.to_vec())?;
    py.run(
        c"from importlib.metadata import distributions\n\
bundled = {name.lower() for name in bundled}\n\
result = sorted({(ep.name, ep.value.split(':')[0].strip()) for dist in distributions() if (dist.metadata['Name'] or '').lower() not in bundled for ep in dist.entry_points if ep.group == 'pytest11'})\n",
        Some(&globals),
        None,
    )?;
    let entrypoints: Vec<(String, String)> = globals
        .get_item("result")?
        .map(|result| result.extract())
        .transpose()?
        .unwrap_or_default();

    for (ep_name, module_name) in entrypoints {
        if blocked.contains(&ep_name) || blocked.contains(&module_name) {
            continue;
        }
        // Already loaded via -p NAME or a conftest's pytest_plugins.
        let already = hooks
            .iter()
            .any(|hook| hook.plugin_module.as_deref() == Some(module_name.as_str()));
        if already {
            continue;
        }
        let plugin = match py.import(module_name.as_str()) {
            Ok(plugin) => plugin,
            Err(err) => {
                let _ = warn_explicit_at(
                    py,
                    "PytestConfigWarning",
                    &format!("could not load plugin '{ep_name}': {}", err.value(py)),
                    module_name.as_str(),
                    0,
                );
                continue;
            }
        };
        register_fixtures_from(py, &plugin, "", registry)?;
        let before = hooks.len();
        scan_py_hooks(&plugin, "", hooks)?;
        for hook in &mut hooks[before..] {
            hook.plugin_module = Some(module_name.clone());
        }
    }
    Ok(())
}

/// Import a conftest.py; its fixtures and pytest_* hooks are visible to
/// all items under its directory.
pub fn collect_conftest(
    py: Python<'_>,
    rootdir: &Path,
    path: &Path,
    registry: &mut FixtureRegistry,
    hooks: &mut Vec<crate::session::PyHook>,
) -> PyResult<()> {
    let (basedir, module_name) = module_name_for(path);
    sys_path_prepend(py, &basedir)?;
    // Conftests in nested directories (without __init__.py) all resolve to
    // the module name "conftest"; a plain import would alias them to the
    // first one imported. Import shadowed ones under a unique name instead.
    let module = match conftest_alias_name(py, &module_name, path)? {
        Some(unique) => import_module_from_path(py, &unique, path)?,
        None => py.import(module_name.as_str())?,
    };
    let dir_nodeid = file_nodeid(rootdir, path.parent().unwrap_or(rootdir));
    let baseid = if dir_nodeid.is_empty() || dir_nodeid == "." {
        String::new()
    } else {
        format!("{dir_nodeid}/")
    };
    // `pytest_plugins = [...]` in a conftest: the named modules' fixtures
    // and hooks register globally. Dotted names ("tests.fixtures.db")
    // resolve against the rootdir.
    sys_path_prepend(py, rootdir)?;
    register_pytest_plugins(py, &module, registry, hooks)?;
    register_fixtures_from(py, &module, &baseid, registry)?;
    scan_py_hooks(&module, &baseid, hooks)
}

/// A unique import name for a conftest whose module name is already taken
/// by a *different* file in sys.modules; None when a plain import is safe.
fn conftest_alias_name(
    py: Python<'_>,
    module_name: &str,
    path: &Path,
) -> PyResult<Option<String>> {
    let sys_modules = py.import("sys")?.getattr("modules")?;
    let Ok(existing) = sys_modules.get_item(module_name) else {
        return Ok(None);
    };
    let same_file = existing
        .getattr("__file__")
        .ok()
        .and_then(|file| file.extract::<String>().ok())
        .map(|file| {
            let existing_path = std::fs::canonicalize(&file).unwrap_or_else(|_| file.into());
            let this_path = std::fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
            existing_path == this_path
        })
        .unwrap_or(false);
    if same_file {
        return Ok(None);
    }
    let suffix: String = path
        .parent()
        .map(|dir| dir.to_string_lossy().replace(['/', '\\', '.', ':'], "_"))
        .unwrap_or_default();
    Ok(Some(format!("{module_name}@{suffix}")))
}

/// Import a module from an explicit file path under the given name
/// (importlib spec machinery; registers it in sys.modules).
fn import_module_from_path<'py>(
    py: Python<'py>,
    name: &str,
    path: &Path,
) -> PyResult<Bound<'py, PyModule>> {
    let sys_modules = py.import("sys")?.getattr("modules")?;
    if let Ok(existing) = sys_modules.get_item(name) {
        return existing.downcast_into::<PyModule>().map_err(Into::into);
    }
    let util = py.import("importlib.util")?;
    let spec = util
        .getattr("spec_from_file_location")?
        .call1((name, path.to_string_lossy().as_ref()))?;
    let module = util.getattr("module_from_spec")?.call1((&spec,))?;
    sys_modules.set_item(name, &module)?;
    spec.getattr("loader")?
        .call_method1("exec_module", (&module,))?;
    module.downcast_into::<PyModule>().map_err(Into::into)
}

/// Build the Config proxy passed to conftest hooks. One proxy per process
/// (the Config itself is process-global), so attribute mutations made by
/// conftest hooks (e.g. `config.option.foo = ...`) stay visible everywhere.
static CONFIG_PROXY: std::sync::OnceLock<Py<PyAny>> = std::sync::OnceLock::new();

/// The process-global Config proxy, if one was built already.
pub fn existing_py_config(py: Python<'_>) -> Option<Py<PyAny>> {
    CONFIG_PROXY.get().map(|proxy| proxy.clone_ref(py))
}

pub fn make_py_config(py: Python<'_>, config: &crate::config::Config) -> PyResult<Py<PyAny>> {
    if let Some(proxy) = CONFIG_PROXY.get() {
        return Ok(proxy.clone_ref(py));
    }
    // `config.option` is the argparse namespace in pytest; expose a mutable
    // namespace so conftests can stash flags on it.
    let option_ns = py.import("types")?.getattr("SimpleNamespace")?.call0()?;
    // Populate doctest-related option attributes so getoption() works.
    option_ns.setattr(
        "doctest_modules",
        config.get_flag("doctest-modules"),
    )?;
    option_ns.setattr(
        "doctest_continue_on_failure",
        config.get_flag("doctest-continue-on-failure"),
    )?;
    option_ns.setattr(
        "doctest_ignore_import_errors",
        config.get_flag("doctest-ignore-import-errors"),
    )?;
    option_ns.setattr(
        "doctest_report",
        config
            .get_value("doctest-report")
            .unwrap_or("none")
            .to_owned(),
    )?;
    // doctest_glob: list of glob patterns (multi-value)
    let glob_list = pyo3::types::PyList::empty(py);
    if let Some(globs) = config.get_values("doctest-glob") {
        for g in globs {
            glob_list.append(g)?;
        }
    }
    option_ns.setattr("doctest_glob", glob_list)?;
    let option = option_ns.unbind();
    let proxy = Py::new(
        py,
        crate::request::PyConfig::new(
            config.rootdir.to_string_lossy().to_string(),
            config.ini_snapshot(),
            option,
        ),
    )?
    .into_any();
    Ok(CONFIG_PROXY.get_or_init(|| proxy).clone_ref(py))
}

fn introspect_namespace(
    py: Python<'_>,
    module: &Bound<'_, PyModule>,
    nodeid_base: &str,
    module_name: &str,
    path: &Path,
    items: &mut Vec<TestItem>,
    registry: &mut FixtureRegistry,
) -> PyResult<()> {
    register_fixtures_from(py, module, &format!("{nodeid_base}::"), registry)?;

    // Module-level `pytestmark` applies to every item in the module.
    let module_marks = read_marks(py, module.as_any())?;

    // A module-level pytest_generate_tests hook parametrizes via metafunc.
    // (conftest-level hooks are not threaded through here yet.)
    let generate_hook: Option<Bound<'_, PyAny>> = module
        .dict()
        .get_item("pytest_generate_tests")?
        .filter(|hook| hook.is_callable());

    let inspect = py.import("inspect")?;
    let isclass = inspect.getattr("isclass")?;
    let dict = module.dict();
    // Module dicts preserve definition order in CPython; keep it.
    for (key, value) in dict.iter() {
        let Ok(name) = key.extract::<String>() else {
            continue;
        };
        if isclass.call1((&value,))?.extract::<bool>()? {
            let is_testcase: bool = py
                .import("pytest._unittest")?
                .getattr("is_testcase_class")?
                .call1((&value,))?
                .extract()?;
            if is_testcase {
                collect_testcase(
                    py,
                    &value,
                    &name,
                    nodeid_base,
                    module_name,
                    path,
                    &module_marks,
                    items,
                )?;
            } else if name.starts_with("Test") {
                collect_class(
                    py,
                    &value,
                    &name,
                    nodeid_base,
                    module_name,
                    path,
                    &module_marks,
                    items,
                    registry,
                    module,
                    generate_hook.as_ref(),
                )?;
            }
            continue;
        }
        // pytest default python_functions = "test*"
        if !name.starts_with("test")
            || !value.is_callable()
            || value.hasattr("_pytestfixturefunction")?
        {
            continue;
        }
        let mut marks = read_marks(py, &value)?;
        marks.extend(clone_marks(py, &module_marks));
        push_test_items(
            py,
            items,
            nodeid_base,
            module_name,
            path,
            &name,
            &value,
            None,
            marks,
            module,
            generate_hook.as_ref(),
        )?;
    }
    Ok(())
}

fn clone_marks(py: Python<'_>, marks: &[MarkData]) -> Vec<MarkData> {
    marks
        .iter()
        .map(|m| MarkData {
            name: m.name.clone(),
            obj: m.obj.clone_ref(py),
        })
        .collect()
}

/// Collect unittest.TestCase test methods as zero-arg runner callables
/// (setUp/method/tearDown handled by the pytest._unittest shim).
#[allow(clippy::too_many_arguments)]
fn collect_testcase(
    py: Python<'_>,
    cls: &Bound<'_, PyAny>,
    cls_name: &str,
    nodeid_base: &str,
    module_name: &str,
    path: &Path,
    module_marks: &[MarkData],
    items: &mut Vec<TestItem>,
) -> PyResult<()> {
    let unittest_shim = py.import("pytest._unittest")?;
    let make_runner = unittest_shim.getattr("make_runner")?;
    let class_nodeid = format!("{nodeid_base}::{cls_name}");
    let mut class_marks = read_marks(py, cls)?;
    class_marks.extend(clone_marks(py, module_marks));

    // dir() includes inherited test methods, matching unittest collection.
    let mut names: Vec<String> = py
        .import("builtins")?
        .getattr("dir")?
        .call1((cls,))?
        .extract()?;
    names.sort();
    for name in names {
        if !name.starts_with("test") {
            continue;
        }
        let Ok(method) = cls.getattr(name.as_str()) else {
            continue;
        };
        if !method.is_callable() {
            continue;
        }
        let mut marks = read_marks(py, &method)?;
        marks.extend(clone_marks(py, &class_marks));
        let runner = make_runner.call1((cls, name.as_str()))?;
        items.push(TestItem {
            nodeid: format!("{class_nodeid}::{name}"),
            path: path.to_path_buf(),
            module_name: module_name.to_string(),
            func_name: name,
            func: runner.unbind(),
            cls: None,
            is_coroutine: false,
            is_doctest: false,
            fixture_names: Vec::new(),
            extra_fixture_names: Vec::new(),
            marks,
            callspec: Vec::new(),
            fixture_params: Vec::new(),
            lineno: first_lineno(py, &method),
        });
    }
    Ok(())
}

/// Collect test methods (and class-level fixtures) from a Test* class.
#[allow(clippy::too_many_arguments)]
fn collect_class(
    py: Python<'_>,
    cls: &Bound<'_, PyAny>,
    cls_name: &str,
    nodeid_base: &str,
    module_name: &str,
    path: &Path,
    module_marks: &[MarkData],
    items: &mut Vec<TestItem>,
    registry: &mut FixtureRegistry,
    module: &Bound<'_, PyModule>,
    generate_hook: Option<&Bound<'_, PyAny>>,
) -> PyResult<()> {
    // Classes with a custom __init__ are not collected (pytest behavior).
    let cls_dict = cls.getattr("__dict__")?;
    if cls_dict.contains("__init__")? {
        return Ok(());
    }
    let class_nodeid = format!("{nodeid_base}::{cls_name}");
    let mut class_marks = read_marks(py, cls)?;
    class_marks.extend(clone_marks(py, module_marks));

    for pair in cls_dict.call_method0("items")?.try_iter()? {
        let (name, value): (String, Bound<'_, PyAny>) = pair?.extract()?;
        // cls.__dict__ stores staticmethods as descriptors; unwrap so mark
        // reading and async introspection see the underlying function.
        let is_static = value.is_instance(&py.import("builtins")?.getattr("staticmethod")?)?;
        let value = if is_static {
            value.getattr("__func__")?
        } else {
            value
        };
        if !value.is_callable() {
            continue;
        }
        if value.hasattr("_pytestfixturefunction")? {
            register_fixture_def(
                py,
                &name,
                &value,
                &format!("{class_nodeid}::"),
                !is_static,
                registry,
            )?;
            continue;
        }
        if !name.starts_with("test") {
            continue;
        }
        let mut marks = read_marks(py, &value)?;
        for mark in &class_marks {
            marks.push(MarkData {
                name: mark.name.clone(),
                obj: mark.obj.clone_ref(py),
            });
        }
        push_test_items(
            py,
            items,
            &class_nodeid,
            module_name,
            path,
            &name,
            &value,
            Some(cls),
            marks,
            module,
            generate_hook,
        )?;
    }
    Ok(())
}

/// Push the (possibly parametrize-expanded) items for one test function.
#[allow(clippy::too_many_arguments)]
fn push_test_items(
    py: Python<'_>,
    items: &mut Vec<TestItem>,
    nodeid_prefix: &str,
    module_name: &str,
    path: &Path,
    name: &str,
    func: &Bound<'_, PyAny>,
    cls: Option<&Bound<'_, PyAny>>,
    marks: Vec<MarkData>,
    module: &Bound<'_, PyModule>,
    generate_hook: Option<&Bound<'_, PyAny>>,
) -> PyResult<()> {
    let flags = async_flags(py, func)?;
    let mut fixture_names = param_names(py, func)?;
    if cls.is_some() && fixture_names.first().map(String::as_str) == Some("self") {
        fixture_names.remove(0);
    }
    // @unittest.mock.patch-injected leading params are not fixture requests.
    let mock_args = num_mock_patch_args(py, func).min(fixture_names.len());
    if mock_args > 0 {
        fixture_names.drain(..mock_args);
    }

    // pytest_generate_tests: metafunc.parametrize calls become parametrize
    // marks, merged after the decorator-applied ones.
    let mut marks = marks;
    if let Some(hook) = generate_hook {
        let metafunc = py.import("pytest._metafunc")?.getattr("Metafunc")?.call1((
            func,
            fixture_names.clone(),
            module,
            cls.map(|c| c.clone().unbind()),
        ))?;
        hook.call1((&metafunc,))?;
        for mark in metafunc.getattr("_parametrize_marks")?.try_iter()? {
            let mark = mark?;
            marks.push(MarkData {
                name: "parametrize".to_string(),
                obj: mark.unbind(),
            });
        }
    }

    let variants = expand_parametrize(py, &marks, &format!("{nodeid_prefix}::{name}"))?;
    for variant in variants {
        let nodeid = match &variant.id {
            Some(id) => format!("{nodeid_prefix}::{name}[{id}]"),
            None => format!("{nodeid_prefix}::{name}"),
        };
        let mut item_marks: Vec<MarkData> = marks
            .iter()
            .map(|m| MarkData {
                name: m.name.clone(),
                obj: m.obj.clone_ref(py),
            })
            .collect();
        item_marks.extend(variant.extra_marks);
        items.push(TestItem {
            nodeid,
            path: path.to_path_buf(),
            module_name: module_name.to_string(),
            func_name: name.to_string(),
            func: func.clone().unbind(),
            cls: cls.map(|c| c.clone().unbind()),
            is_coroutine: flags.is_coroutine,
            is_doctest: false,
            fixture_names: fixture_names.clone(),
            extra_fixture_names: Vec::new(),
            marks: item_marks,
            callspec: variant.params,
            fixture_params: Vec::new(),
            lineno: first_lineno(py, func),
        });
    }
    Ok(())
}

struct ParamVariant {
    /// The "[...]" id suffix; None for unparametrized tests.
    id: Option<String>,
    params: Vec<(String, Py<PyAny>)>,
    /// Marks attached via pytest.param(..., marks=...).
    extra_marks: Vec<MarkData>,
}

/// Expand stacked @pytest.mark.parametrize marks into the cartesian product
/// of parameter sets. Marks appear in pytestmark order (bottom decorator
/// first); ids join in that order and later marks vary fastest.
fn expand_parametrize(
    py: Python<'_>,
    marks: &[MarkData],
    nodeid: &str,
) -> PyResult<Vec<ParamVariant>> {
    struct ParamSet {
        /// None hides the set from the test ID (pytest.HIDDEN_PARAM).
        id_part: Option<String>,
        params: Vec<(String, Py<PyAny>)>,
        extra_marks: Vec<MarkData>,
    }
    struct Dim {
        sets: Vec<ParamSet>,
    }

    let param_spec_cls = py.import("pytest")?.getattr("ParamSpec")?;
    let hidden_param = py.import("pytest")?.getattr("HIDDEN_PARAM")?;
    // Armed by configure_mark_generator once the session config is known.
    let strict_ids = py
        .import("pytest._marks")
        .and_then(|m| m.getattr("mark"))
        .and_then(|mark| mark.getattr("_strict_parametrization_ids"))
        .and_then(|v| v.extract::<bool>())
        .unwrap_or(false);
    let mut dims: Vec<Dim> = Vec::new();

    for mark in marks.iter().filter(|m| m.name == "parametrize") {
        let args = mark.obj.bind(py).getattr("args")?;
        let argnames_obj = args.get_item(0)?;
        let argvalues = args.get_item(1)?;
        // pytest's force_tuple: only a single argname given as a *string*
        // takes each argvalue as the bare value; a one-element list
        // (["x"]) still expects one-element value collections.
        let (argnames, force_scalar): (Vec<String>, bool) = match argnames_obj.extract::<String>()
        {
            Ok(joined) => {
                let names: Vec<String> =
                    joined.split(',').map(|s| s.trim().to_string()).collect();
                let single = names.len() == 1;
                (names, single)
            }
            Err(_) => (argnames_obj.extract()?, false),
        };
        let explicit_ids: Option<Vec<Option<String>>> = mark
            .obj
            .bind(py)
            .getattr("kwargs")?
            .get_item("ids")
            .ok()
            .and_then(|ids| ids.extract().ok());

        let mut sets = Vec::new();
        for (index, value_set) in argvalues.try_iter()?.enumerate() {
            let value_set = value_set?;
            let (values, spec_id, hidden, extra_marks) = if value_set
                .is_instance(&param_spec_cls)?
            {
                let values: Vec<Bound<'_, PyAny>> = value_set
                    .getattr("values")?
                    .try_iter()?
                    .collect::<PyResult<_>>()?;
                let id_obj = value_set.getattr("id")?;
                let (spec_id, hidden) = if id_obj.is(&hidden_param) {
                    (None, true)
                } else {
                    (id_obj.extract::<Option<String>>()?, false)
                };
                let extra_marks = value_set
                    .getattr("marks")?
                    .try_iter()?
                    .map(|m| {
                        let m = m?;
                        Ok(MarkData {
                            name: m.getattr("name")?.extract()?,
                            obj: m.unbind(),
                        })
                    })
                    .collect::<PyResult<Vec<_>>>()?;
                (values, spec_id, hidden, extra_marks)
            } else if force_scalar {
                (vec![value_set], None, false, Vec::new())
            } else {
                let values: Vec<Bound<'_, PyAny>> =
                    value_set.try_iter()?.collect::<PyResult<_>>()?;
                (values, None, false, Vec::new())
            };

            if values.len() != argnames.len() {
                return Err(pyo3::exceptions::PyValueError::new_err(format!(
                    "parametrize: {} argnames but {} values",
                    argnames.len(),
                    values.len()
                )));
            }

            let id_part = if hidden {
                None
            } else {
                Some(
                    spec_id
                        .or_else(|| {
                            explicit_ids
                                .as_ref()
                                .and_then(|ids| ids.get(index).cloned().flatten())
                        })
                        .unwrap_or_else(|| {
                            let parts: Vec<String> = argnames
                                .iter()
                                .zip(values.iter())
                                .map(|(argname, value)| id_for_value(value, argname, index))
                                .collect();
                            parts.join("-")
                        }),
                )
            };
            let params: Vec<(String, Py<PyAny>)> = argnames
                .iter()
                .cloned()
                .zip(values.into_iter().map(Bound::unbind))
                .collect();
            sets.push(ParamSet {
                id_part,
                params,
                extra_marks,
            });
        }
        // pytest's make_unique_parameterset_ids: duplicate IDs within one
        // parametrize call either error out (strict_parametrization_ids)
        // or get a counter suffix ("_" separator after a trailing digit).
        let mut counts: std::collections::HashMap<Option<String>, usize> =
            std::collections::HashMap::new();
        for set in &sets {
            *counts.entry(set.id_part.clone()).or_default() += 1;
        }
        if counts.values().any(|&count| count > 1) {
            let display =
                |id: &Option<String>| id.clone().unwrap_or_else(|| "<hidden>".to_string());
            if strict_ids {
                let mut reprs = Vec::new();
                for set in &sets {
                    let values =
                        PyList::new(py, set.params.iter().map(|(_, value)| value.bind(py)))?;
                    reprs.push(values.repr()?.to_string());
                }
                let mut seen = std::collections::HashSet::new();
                let duplicates: Vec<String> = sets
                    .iter()
                    .filter(|set| counts[&set.id_part] > 1)
                    .filter(|set| seen.insert(set.id_part.clone()))
                    .map(|set| display(&set.id_part))
                    .collect();
                let ids: Vec<String> = sets.iter().map(|set| display(&set.id_part)).collect();
                let message = format!(
                    "Duplicate parametrization IDs detected, but strict_parametrization_ids is set.\n\
                     \n\
                     Test name:      {nodeid}\n\
                     Parameters:     {}\n\
                     Parameter sets: {}\n\
                     IDs:            {}\n\
                     Duplicates:     {}\n\
                     \n\
                     You can fix this problem using `@pytest.mark.parametrize(..., ids=...)` or `pytest.param(..., id=...)`.",
                    argnames.join(", "),
                    reprs.join(", "),
                    ids.join(", "),
                    duplicates.join(", "),
                );
                return Err(collect_error(py, &message));
            }
            if counts.get(&None).copied().unwrap_or(0) > 1 {
                return Err(collect_error(
                    py,
                    &format!(
                        "In {nodeid}: multiple instances of HIDDEN_PARAM cannot be used in \
                         the same parametrize call, because the tests names need to be unique."
                    ),
                ));
            }
            let mut existing: std::collections::HashSet<String> =
                sets.iter().filter_map(|set| set.id_part.clone()).collect();
            let mut suffixes: std::collections::HashMap<String, usize> =
                std::collections::HashMap::new();
            for index in 0..sets.len() {
                let Some(id) = sets[index].id_part.clone() else {
                    continue;
                };
                if counts[&Some(id.clone())] <= 1 {
                    continue;
                }
                let sep = if id.chars().last().is_some_and(|c| c.is_ascii_digit()) {
                    "_"
                } else {
                    ""
                };
                let counter = suffixes.entry(id.clone()).or_insert(0);
                let mut new_id = format!("{id}{sep}{counter}");
                while existing.contains(&new_id) {
                    *counter += 1;
                    new_id = format!("{id}{sep}{counter}");
                }
                existing.insert(new_id.clone());
                sets[index].id_part = Some(new_id);
                *counter += 1;
            }
        }
        dims.push(Dim { sets });
    }

    if dims.is_empty() {
        return Ok(vec![ParamVariant {
            id: None,
            params: Vec::new(),
            extra_marks: Vec::new(),
        }]);
    }
    // An empty parameter set produces no items (pytest marks one skipped;
    // zero items is the closest simple behavior).
    if dims.iter().any(|dim| dim.sets.is_empty()) {
        return Ok(Vec::new());
    }

    // Odometer over dims; the last dim varies fastest, ids join in dim order.
    let mut variants = Vec::new();
    let mut indices = vec![0usize; dims.len()];
    'outer: loop {
        let mut id_parts = Vec::new();
        let mut params = Vec::new();
        let mut extra_marks = Vec::new();
        for (dim, &index) in dims.iter().zip(indices.iter()) {
            let set = &dim.sets[index];
            // HIDDEN_PARAM sets contribute nothing to the test ID.
            if let Some(part) = &set.id_part {
                id_parts.push(part.clone());
            }
            for (name, value) in &set.params {
                params.push((name.clone(), value.clone_ref(py)));
            }
            for mark in &set.extra_marks {
                extra_marks.push(MarkData {
                    name: mark.name.clone(),
                    obj: mark.obj.clone_ref(py),
                });
            }
        }
        variants.push(ParamVariant {
            // All-hidden variants keep the bare test name (no brackets).
            id: (!id_parts.is_empty()).then(|| id_parts.join("-")),
            params,
            extra_marks,
        });

        for pos in (0..dims.len()).rev() {
            indices[pos] += 1;
            if indices[pos] < dims[pos].sets.len() {
                continue 'outer;
            }
            indices[pos] = 0;
            if pos == 0 {
                break 'outer;
            }
        }
    }
    Ok(variants)
}

/// A pytest.Collector.CollectError carrying `message`: collection fails
/// with the message shown bare (no traceback) in the ERRORS section.
fn collect_error(py: Python<'_>, message: &str) -> PyErr {
    let cls = py
        .import("pytest")
        .and_then(|m| m.getattr("Collector"))
        .and_then(|c| c.getattr("CollectError"));
    match cls {
        Ok(cls) => match cls.call1((message,)) {
            Ok(instance) => PyErr::from_value(instance),
            Err(err) => err,
        },
        Err(err) => err,
    }
}

/// Some(message) when `err` is a CollectError, shown without a traceback.
pub fn collect_error_message(py: Python<'_>, err: &PyErr) -> Option<String> {
    let cls = py
        .import("pytest")
        .and_then(|m| m.getattr("Collector"))
        .and_then(|c| c.getattr("CollectError"))
        .ok()?;
    err.matches(py, &cls)
        .unwrap_or(false)
        .then(|| err.value(py).to_string())
}

/// pytest-style id for one parameter value.
fn id_for_value(value: &Bound<'_, PyAny>, argname: &str, index: usize) -> String {
    if value.is_none() {
        return "None".to_string();
    }
    if let Ok(b) = value.cast::<pyo3::types::PyBool>() {
        return if b.is_true() { "True" } else { "False" }.to_string();
    }
    if let Ok(s) = value.extract::<String>() {
        return s;
    }
    if (value.cast::<pyo3::types::PyInt>().is_ok() || value.cast::<pyo3::types::PyFloat>().is_ok())
        && let Ok(repr) = value.repr()
    {
        return repr.to_string();
    }
    format!("{argname}{index}")
}

fn register_fixtures_from(
    py: Python<'_>,
    module: &Bound<'_, PyModule>,
    baseid: &str,
    registry: &mut FixtureRegistry,
) -> PyResult<()> {
    for (key, value) in module.dict().iter() {
        let Ok(attr_name) = key.extract::<String>() else {
            continue;
        };
        if !value.is_callable() || !value.hasattr("_pytestfixturefunction")? {
            continue;
        }
        register_fixture_def(py, &attr_name, &value, baseid, false, registry)?;
    }
    Ok(())
}

pub(crate) fn register_fixture_def(
    py: Python<'_>,
    attr_name: &str,
    value: &Bound<'_, PyAny>,
    baseid: &str,
    needs_instance: bool,
    registry: &mut FixtureRegistry,
) -> PyResult<()> {
    let marker = value.getattr("_pytestfixturefunction")?;
    // Defensive: objects faking the marker attribute (stubs, mocks) are
    // skipped rather than failing collection.
    let Ok(scope_str) = marker
        .getattr("scope")
        .and_then(|scope| scope.extract::<String>())
    else {
        return Ok(());
    };
    let scope_str: String = scope_str;
    let scope = Scope::parse(&scope_str).unwrap_or(Scope::Function);
    let autouse: bool = marker.getattr("autouse")?.extract()?;
    let explicit_name: Option<String> = marker.getattr("name")?.extract()?;
    let name = explicit_name.unwrap_or_else(|| attr_name.to_string());
    let flags = async_flags(py, value)?;
    let mut param_names = param_names(py, value)?;
    if needs_instance && param_names.first().map(String::as_str) == Some("self") {
        param_names.remove(0);
    }
    let params_obj = marker.getattr("params")?;
    let params = if params_obj.is_none() {
        None
    } else {
        Some(params_obj.unbind())
    };
    registry.register(FixtureDef {
        name,
        func: value.clone().unbind(),
        scope,
        autouse,
        is_coroutine: flags.is_coroutine,
        is_generator: flags.is_generator,
        is_async_gen: flags.is_async_gen,
        param_names,
        baseid: baseid.to_string(),
        needs_instance,
        params,
    });
    Ok(())
}

/// Expand items over parametrized fixtures in their closure: an item using
/// a fixture with `params=[...]` becomes one item per param value, with the
/// param id appended to the nodeid.
pub fn expand_fixture_params(
    py: Python<'_>,
    items: Vec<TestItem>,
    registry: &FixtureRegistry,
) -> PyResult<Vec<TestItem>> {
    let mut expanded = Vec::new();
    for item in items {
        let parametrized: Vec<_> = registry
            .closure_for(&item.nodeid, &item.fixture_names)
            .into_iter()
            .filter(|def| def.params.is_some())
            .collect();
        if parametrized.is_empty() {
            expanded.push(item);
            continue;
        }

        // Cartesian product over each parametrized fixture's values.
        type Assignment = (String, usize, Py<PyAny>);
        let mut variants: Vec<(String, Vec<Assignment>)> = vec![(String::new(), Vec::new())];
        for def in &parametrized {
            let values: Vec<Bound<'_, PyAny>> = def
                .params
                .as_ref()
                .expect("filtered to Some above")
                .bind(py)
                .try_iter()?
                .collect::<PyResult<_>>()?;
            let mut next = Vec::new();
            for (id, assignments) in &variants {
                for (index, value) in values.iter().enumerate() {
                    let part = id_for_value(value, &def.name, index);
                    let id = if id.is_empty() {
                        part
                    } else {
                        format!("{id}-{part}")
                    };
                    let mut assignments = assignments
                        .iter()
                        .map(|(n, i, v)| (n.clone(), *i, v.clone_ref(py)))
                        .collect::<Vec<_>>();
                    assignments.push((def.name.clone(), index, value.clone().unbind()));
                    next.push((id, assignments));
                }
            }
            variants = next;
        }

        for (id, assignments) in variants {
            let nodeid = if item.nodeid.ends_with(']') {
                format!("{}-{id}]", &item.nodeid[..item.nodeid.len() - 1])
            } else {
                format!("{}[{id}]", item.nodeid)
            };
            expanded.push(TestItem {
                nodeid,
                path: item.path.clone(),
                module_name: item.module_name.clone(),
                func_name: item.func_name.clone(),
                func: item.func.clone_ref(py),
                cls: item.cls.as_ref().map(|c| c.clone_ref(py)),
                is_coroutine: item.is_coroutine,
                is_doctest: item.is_doctest,
                lineno: item.lineno,
                fixture_names: item.fixture_names.clone(),
                extra_fixture_names: item.extra_fixture_names.clone(),
                marks: item
                    .marks
                    .iter()
                    .map(|m| MarkData {
                        name: m.name.clone(),
                        obj: m.obj.clone_ref(py),
                    })
                    .collect(),
                callspec: item
                    .callspec
                    .iter()
                    .map(|(n, v)| (n.clone(), v.clone_ref(py)))
                    .collect(),
                fixture_params: assignments,
            });
        }
    }
    Ok(expanded)
}

/// Read `pytestmark` from a function, class, or module. Accepts a single
/// mark or a list, and normalizes bare MarkDecorators (e.g.
/// `pytestmark = pytest.mark.asyncio`) to their Mark.
fn read_marks(py: Python<'_>, obj: &Bound<'_, PyAny>) -> PyResult<Vec<MarkData>> {
    let mut marks = Vec::new();
    let Ok(pytestmark) = obj.getattr("pytestmark") else {
        return Ok(marks);
    };
    let entries: Vec<Bound<'_, PyAny>> = match pytestmark.try_iter() {
        Ok(iter) => iter.collect::<PyResult<_>>()?,
        Err(_) => vec![pytestmark],
    };
    for entry in entries {
        // A bare MarkDecorator carries the Mark in its `mark` attribute.
        let mark = match entry.getattr("mark") {
            Ok(inner) if inner.hasattr("name")? => inner,
            _ => entry,
        };
        // Defensive: skip entries without a string name (stubs, mocks).
        let Ok(name) = mark.getattr("name").and_then(|n| n.extract::<String>()) else {
            continue;
        };
        marks.push(MarkData {
            name,
            obj: mark.unbind(),
        });
    }
    let _ = py;
    Ok(marks)
}

/// Format a PyErr as a native-style traceback string.
pub fn format_exception(py: Python<'_>, err: &PyErr) -> String {
    let result: PyResult<String> = (|| {
        let traceback = py.import("traceback")?;
        let formatted = traceback.call_method1("format_exception", (err.value(py),))?;
        let lines: Vec<String> = formatted.extract()?;
        Ok(lines.join(""))
    })();
    result.unwrap_or_else(|_| format!("{err}"))
}

/// Format a test failure pytest-style (per --tb), falling back to the
/// native traceback.
pub fn format_test_failure(py: Python<'_>, err: &PyErr, style: &str) -> String {
    let result: PyResult<String> = (|| {
        py.import("pytest._tb")?
            .call_method1("format_exception", (err.value(py), style))?
            .extract()
    })();
    result.unwrap_or_else(|_| format_exception(py, err))
}

/// An explicit "file.py:line" the raiser attached to a Skipped exception
/// (`_location`), overriding traceback-derived skip locations.
pub fn skip_location_override(py: Python<'_>, err: &PyErr) -> Option<String> {
    err.value(py).getattr("_location").ok()?.extract().ok()
}

/// Tell the subtests fixture how many failures remain in the --maxfail
/// budget (None = unlimited); exhausting it stops swallowing failures.
pub fn set_subtest_fail_budget(py: Python<'_>, budget: Option<usize>) {
    let _ = (|| -> PyResult<()> {
        py.import("pytest._subtests")?
            .getattr("set_fail_budget")?
            .call1((budget,))?;
        Ok(())
    })();
}

/// Drain the subtests fixture accumulator into reports for this item.
/// Quiet subtest verbosity (the default) keeps only failed subtests,
/// matching upstream's pytest_report_teststatus filtering. The second
/// value counts failed fixture subtests (unittest subTest failures do
/// not fail the enclosing test upstream, so they are excluded).
pub fn pop_subtest_reports(
    py: Python<'_>,
    config: &crate::config::Config,
    item: &TestItem,
    quiet: bool,
) -> (Vec<crate::report::TestReport>, usize) {
    let result: PyResult<(Vec<crate::report::TestReport>, usize)> = (|| {
        let module = py.import("pytest._subtests")?;
        let results = module.getattr("pop_results")?.call0()?;
        let style = config.get_value("tb").unwrap_or("long").to_string();
        let mut reports = Vec::new();
        let mut failed_fixture_subs = 0usize;
        for record in results.try_iter()? {
            let record = record?;
            let outcome_str: String = record.get_item("outcome")?.extract()?;
            let desc: String = record.get_item("desc")?.extract()?;
            let duration: f64 = record.get_item("duration")?.extract()?;
            let reason: String = record.get_item("reason")?.extract()?;
            let location: Option<String> = record.get_item("location")?.extract()?;
            let from_unittest: bool = record
                .call_method1("get", ("unittest", false))?
                .extract()
                .unwrap_or(false);
            let (outcome, longrepr) = match outcome_str.as_str() {
                "failed" => {
                    let exc = record.get_item("exc")?;
                    let err = PyErr::from_value(exc);
                    if !from_unittest {
                        failed_fixture_subs += 1;
                    }
                    (
                        crate::report::Outcome::Failed,
                        Some(format_test_failure(py, &err, &style)),
                    )
                }
                "skipped" => (crate::report::Outcome::Skipped, Some(reason)),
                "xfailed" => (crate::report::Outcome::XFailed, Some(reason)),
                _ => (crate::report::Outcome::Passed, None),
            };
            if quiet && outcome != crate::report::Outcome::Failed {
                continue;
            }
            reports.push(crate::report::TestReport {
                nodeid: item.nodeid.clone(),
                phase: crate::report::Phase::Call,
                outcome,
                duration: std::time::Duration::from_secs_f64(duration),
                longrepr,
                location,
                subtest_desc: Some(desc),
            });
        }
        Ok((reports, failed_fixture_subs))
    })();
    result.unwrap_or_default()
}

/// Build a `pytest._node.Node` for an item (used as `request.node`).
pub fn make_node(py: Python<'_>, item: &TestItem) -> PyResult<Py<PyAny>> {
    let marks = pyo3::types::PyList::empty(py);
    for mark in &item.marks {
        marks.append(mark.obj.bind(py))?;
    }
    let fixturenames = pyo3::types::PyList::new(
        py,
        item.fixture_names
            .iter()
            .chain(&item.extra_fixture_names)
            .collect::<Vec<_>>(),
    )?;
    // node.name is the last nodeid segment, parametrization id included
    // ("test_foo[a-1]"), matching pytest.
    let name = item
        .nodeid
        .rsplit("::")
        .next()
        .unwrap_or(item.func_name.as_str());
    let node_cls = if item.is_doctest { "DoctestNode" } else { "Node" };
    let node = py
        .import("pytest._node")?
        .getattr(node_cls)?
        .call1((item.nodeid.as_str(), name, marks, fixturenames, item.func.bind(py)))?;
    Ok(node.unbind())
}

/// Scan a conftest module for pytest_* hook functions.
pub fn scan_py_hooks(
    module: &Bound<'_, PyModule>,
    baseid: &str,
    hooks: &mut Vec<crate::session::PyHook>,
) -> PyResult<()> {
    for (key, value) in module.dict().iter() {
        let Ok(name) = key.extract::<String>() else {
            continue;
        };
        if name.starts_with("pytest_") && value.is_callable() {
            hooks.push(crate::session::PyHook {
                name,
                func: value.unbind(),
                baseid: baseid.to_string(),
                plugin_module: None,
            });
        }
    }
    Ok(())
}

/// Call a conftest hook with only the keyword arguments its signature
/// requests. Generator hooks (pytest wrapper style: `return (yield)`) are
/// driven to completion: setup before the yield, the rest right after.
pub fn call_py_hook(
    py: Python<'_>,
    func: &Py<PyAny>,
    available: &[(&str, Py<PyAny>)],
) -> PyResult<Py<PyAny>> {
    let func = func.bind(py);
    let accepted = param_names(py, func)?;
    let kwargs = PyDict::new(py);
    for (name, value) in available {
        if accepted.iter().any(|param| param == name) {
            kwargs.set_item(name, value.bind(py))?;
        }
    }
    let empty = pyo3::types::PyTuple::empty(py);
    let result = func.call(empty, Some(&kwargs))?;

    let inspect = py.import("inspect")?;
    let is_generator: bool = inspect
        .getattr("isgenerator")?
        .call1((&result,))?
        .extract()?;
    if !is_generator {
        return Ok(result.unbind());
    }
    // Drive the wrapper: run to the yield, then to completion.
    let next_fn = py.import("builtins")?.getattr("next")?;
    if let Err(err) = next_fn.call1((&result,)) {
        if err.is_instance_of::<pyo3::exceptions::PyStopIteration>(py) {
            return Ok(py.None());
        }
        return Err(err);
    }
    match result.call_method1("send", (py.None(),)) {
        Ok(_) => Err(pyo3::exceptions::PyRuntimeError::new_err(
            "conftest hook wrapper yielded more than once",
        )),
        Err(err) if err.is_instance_of::<pyo3::exceptions::PyStopIteration>(py) => Ok(py.None()),
        Err(err) => Err(err),
    }
}

/// Evaluate a (skipif) condition string in a test module's namespace.
pub fn eval_in_module(py: Python<'_>, module_name: &str, expr: &str) -> PyResult<bool> {
    let module = py.import(module_name)?;
    let globals = module.dict();
    let code = std::ffi::CString::new(expr)
        .map_err(|e| pyo3::exceptions::PyValueError::new_err(e.to_string()))?;
    py.eval(code.as_c_str(), Some(&globals), None)?.is_truthy()
}

/// Install session-wide warning capture (pytest default filters), then
/// apply the `filterwarnings` ini lines and -W specs on top (-W last, so
/// the command line takes precedence over the config file).
pub fn install_warning_capture(
    py: Python<'_>,
    ini_specs: &[String],
    w_specs: &[String],
) -> PyResult<()> {
    let wcapture = py.import("pytest._wcapture")?;
    wcapture.call_method0("install")?;
    let ini: Vec<String> = ini_specs.iter().map(|s| s.trim().to_string()).collect();
    let w: Vec<String> = w_specs.iter().map(|s| s.trim().to_string()).collect();
    wcapture.call_method1("apply_session_filters", (ini, w))?;
    Ok(())
}

/// The `config.cache` object (a pytest._cache.Cache) for this run.
fn cache_object<'py>(
    py: Python<'py>,
    config: &crate::config::Config,
) -> PyResult<Bound<'py, PyAny>> {
    let proxy = make_py_config(py, config)?;
    proxy.bind(py).getattr("cache")
}

/// Nodeids recorded as failed in cache/lastfailed (insertion order).
pub fn cache_lastfailed(py: Python<'_>, config: &crate::config::Config) -> Vec<String> {
    let read = || -> PyResult<Vec<String>> {
        let cache = cache_object(py, config)?;
        let value = cache.call_method1("get", ("cache/lastfailed", pyo3::types::PyDict::new(py)))?;
        // dict_keys is not extractable directly; materialize a list first.
        py.import("builtins")?
            .getattr("list")?
            .call1((value.call_method0("keys")?,))?
            .extract()
    };
    read().unwrap_or_default()
}

/// Persist cache/lastfailed and cache/nodeids at session end (done from the
/// pytest.cacheprovider shim so cache warnings carry pytest's locations).
pub fn cache_write_session(
    py: Python<'_>,
    config: &crate::config::Config,
    failed: &[String],
    nodeids: &[String],
) -> PyResult<()> {
    let dict = pyo3::types::PyDict::new(py);
    for nodeid in failed {
        dict.set_item(nodeid, true)?;
    }
    let proxy = make_py_config(py, config)?;
    py.import("pytest.cacheprovider")?.call_method1(
        "write_session_cache",
        (proxy, dict, nodeids.to_vec()),
    )?;
    Ok(())
}

/// Nodeids seen in previous runs (cache/nodeids).
pub fn cache_nodeids(py: Python<'_>, config: &crate::config::Config) -> Vec<String> {
    let read = || -> PyResult<Vec<String>> {
        let cache = cache_object(py, config)?;
        let value = cache.call_method1("get", ("cache/nodeids", pyo3::types::PyList::empty(py)))?;
        value.extract()
    };
    read().unwrap_or_default()
}


/// --cache-show: print cache values/directories matching the glob.
pub fn cache_show(py: Python<'_>, config: &crate::config::Config, glob: &str) -> PyResult<()> {
    let cache = cache_object(py, config)?;
    let cachedir = cache.getattr("_cachedir")?;
    py.import("pytest._cache")?
        .call_method1("cacheshow", (cachedir, glob))?;
    Ok(())
}

/// --cache-clear: drop the cache's value/directory stores at startup.
pub fn cache_clear(py: Python<'_>, config: &crate::config::Config) -> PyResult<()> {
    cache_object(py, config)?.call_method0("clear_cache")?;
    Ok(())
}

/// Expand `testpaths` ini globs against the rootdir (sorted per entry,
/// recursive ** supported), pytest's Config._decide_args.
pub fn glob_testpaths(
    py: Python<'_>,
    rootdir: &Path,
    entries: &[String],
) -> PyResult<Vec<String>> {
    let glob = py.import("glob")?;
    let kwargs = pyo3::types::PyDict::new(py);
    kwargs.set_item("recursive", true)?;
    let mut out = Vec::new();
    for entry in entries {
        let pattern = rootdir.join(entry);
        let mut matches: Vec<String> = glob
            .call_method("glob", (pattern.to_string_lossy().as_ref(),), Some(&kwargs))?
            .extract()?;
        matches.sort();
        out.extend(matches);
    }
    Ok(out)
}

/// Arm the shim's MarkGenerator: unknown marks (not builtin, not in the
/// `markers` ini) warn PytestUnknownMarkWarning at the use site.
pub fn configure_mark_generator(
    py: Python<'_>,
    config: &crate::config::Config,
    strict: bool,
    strict_parametrization_ids: bool,
) -> PyResult<()> {
    let proxy = make_py_config(py, config)?;
    py.import("pytest._marks")?.call_method1(
        "configure_mark_generator",
        (
            proxy,
            crate::engine::BUILTIN_MARKS.to_vec(),
            strict,
            strict_parametrization_ids,
        ),
    )?;
    Ok(())
}

/// Apply per-item @pytest.mark.filterwarnings specs inside a
/// catch_warnings block; returns the context to close at item end.
pub fn begin_item_filters(py: Python<'_>, specs: &[String]) -> PyResult<Py<PyAny>> {
    let ctx = py
        .import("pytest._wcapture")?
        .call_method1("begin_item_filters", (specs.to_vec(),))?;
    Ok(ctx.unbind())
}

pub fn end_item_filters(py: Python<'_>, ctx: &Py<PyAny>) {
    let _ = py
        .import("pytest._wcapture")
        .and_then(|m| m.call_method1("end_item_filters", (ctx.bind(py),)));
}

/// Number of warnings captured so far in this session.
/// Begin a logging capture phase for the current item (pytest's
/// catching_logs around setup/call/teardown). Best-effort.
pub fn log_start_phase(py: Python<'_>, when: &str, level: Option<&str>) {
    let _ = py
        .import("pytest._logging")
        .and_then(|m| m.call_method1("start_phase", (when, level)));
}

/// Close the current item's logging capture (end of teardown).
pub fn log_finish_item(py: Python<'_>) {
    let _ = py
        .import("pytest._logging")
        .and_then(|m| m.call_method0("finish_item"));
}

/// "Captured log {when}" report sections accumulated for the running item.
pub fn log_failure_sections(py: Python<'_>) -> Vec<(String, String)> {
    py.import("pytest._logging")
        .and_then(|m| m.call_method0("failure_sections"))
        .and_then(|sections| sections.extract())
        .unwrap_or_default()
}

pub fn warning_count(py: Python<'_>) -> usize {
    py.import("pytest._wcapture")
        .and_then(|m| m.call_method0("count"))
        .and_then(|count| count.extract())
        .unwrap_or(0)
}

/// Formatted lines for the warnings summary section.
pub fn warning_summary_lines(py: Python<'_>) -> Vec<String> {
    py.import("pytest._wcapture")
        .and_then(|m| m.call_method0("summary_lines"))
        .and_then(|lines| lines.extract())
        .unwrap_or_default()
}

/// Emit a warning of a pytest category attributed to an explicit
/// file/line (registry=None: never deduplicated).
pub fn warn_explicit_at(
    py: Python<'_>,
    category: &str,
    message: &str,
    filename: &str,
    lineno: u32,
) -> PyResult<()> {
    let category = py.import("pytest")?.getattr(category)?;
    py.import("warnings")?
        .call_method1("warn_explicit", (message, category, filename, lineno))?;
    Ok(())
}

/// Construct a pytest.UsageError as a PyErr.
pub fn usage_error(py: Python<'_>, message: &str) -> PyErr {
    let result: PyResult<PyErr> = (|| {
        let cls = py.import("pytest")?.getattr("UsageError")?;
        Ok(PyErr::from_value(cls.call1((message,))?))
    })();
    result.unwrap_or_else(|_| pyo3::exceptions::PyRuntimeError::new_err(message.to_string()))
}

/// Is this error a pytest.UsageError?
pub fn is_usage_error(py: Python<'_>, err: &PyErr) -> bool {
    py.import("pytest")
        .and_then(|m| m.getattr("UsageError"))
        .map(|cls| err.matches(py, &cls).unwrap_or(false))
        .unwrap_or(false)
}

/// Is this error an instance of the shim's `Skipped` outcome?
pub fn is_skipped(py: Python<'_>, err: &PyErr) -> bool {
    err_matches_shim(py, err, "Skipped")
}

/// The session exit code this error forces, if it is a session-aborting
/// one: pytest.exit (its returncode, default INTERRUPTED) or Ctrl-C.
/// The "!!! ... !!!" banner text for a session abort (pytest.exit /
/// Ctrl-C), e.g. "_pytest.outcomes.Exit: foo".
pub fn session_abort_banner(py: Python<'_>, err: &PyErr) -> Option<String> {
    if err.is_instance_of::<pyo3::exceptions::PyKeyboardInterrupt>(py) {
        return Some("KeyboardInterrupt".to_string());
    }
    if err_matches_shim(py, err, "Exit") {
        let msg: String = err
            .value(py)
            .getattr("msg")
            .ok()
            .and_then(|msg| msg.extract().ok())
            .unwrap_or_default();
        return Some(if msg.is_empty() {
            "_pytest.outcomes.Exit".to_string()
        } else {
            format!("_pytest.outcomes.Exit: {msg}")
        });
    }
    None
}

pub fn session_abort_code(py: Python<'_>, err: &PyErr) -> Option<i32> {
    if err.is_instance_of::<pyo3::exceptions::PyKeyboardInterrupt>(py) {
        return Some(crate::report::exit_code::INTERRUPTED);
    }
    if err_matches_shim(py, err, "Exit") {
        let code = err
            .value(py)
            .getattr("returncode")
            .ok()
            .and_then(|code| code.extract::<i32>().ok())
            .unwrap_or(crate::report::exit_code::INTERRUPTED);
        return Some(code);
    }
    None
}

/// Classify a module-import error as a module-level skip.
/// Some(Ok(reason)): the whole module skips (allow_module_level=True or
/// unittest.SkipTest). Some(Err(message)): pytest.skip misused at module
/// level. None: not a skip at all.
pub fn module_level_skip(py: Python<'_>, err: &PyErr) -> Option<Result<String, String>> {
    let skiptest = py
        .import("unittest")
        .and_then(|m| m.getattr("SkipTest"))
        .ok();
    if let Some(skiptest) = skiptest
        && err.matches(py, &skiptest).unwrap_or(false)
    {
        return Some(Ok(err.value(py).to_string()));
    }
    if !is_skipped(py, err) {
        return None;
    }
    let value = err.value(py);
    let allowed = value
        .getattr("allow_module_level")
        .and_then(|allow| allow.extract::<bool>())
        .unwrap_or(false);
    if allowed {
        let reason = value
            .getattr("msg")
            .ok()
            .and_then(|msg| msg.extract::<String>().ok())
            .unwrap_or_default();
        Some(Ok(reason))
    } else {
        Some(Err(
            "Using pytest.skip outside of a test will skip the entire module. \
             If that's your intention, pass `allow_module_level=True` instead."
                .to_string(),
        ))
    }
}

/// Is this error an instance of the shim's `XFailed` outcome?
pub fn is_xfailed(py: Python<'_>, err: &PyErr) -> bool {
    err_matches_shim(py, err, "XFailed")
}

fn err_matches_shim(py: Python<'_>, err: &PyErr, class_name: &str) -> bool {
    py.import("pytest")
        .and_then(|m| m.getattr(class_name))
        .map(|cls| err.matches(py, &cls).unwrap_or(false))
        .unwrap_or(false)
}

/// Outcome message (e.g. skip reason) from a shim OutcomeException.
pub fn outcome_msg(py: Python<'_>, err: &PyErr) -> Option<String> {
    err.value(py)
        .getattr("msg")
        .ok()
        .and_then(|m| m.extract::<Option<String>>().ok())
        .flatten()
}

/// "relpath:lineno" of the frame that raised, for -r summary grouping.
pub fn raise_location(py: Python<'_>, err: &PyErr) -> Option<String> {
    let tb_module = py.import("pytest._tb").ok()?;
    tb_module
        .getattr("raise_location")
        .ok()?
        .call1((err.value(py),))
        .ok()?
        .extract::<Option<String>>()
        .ok()
        .flatten()
}

/// Call a Python callable with keyword arguments resolved from fixtures.
pub fn call_with_kwargs<'py>(
    py: Python<'py>,
    func: &Py<PyAny>,
    kwargs: &[(String, Py<PyAny>)],
) -> PyResult<Bound<'py, PyAny>> {
    call_fixture(py, func, None, kwargs)
}

/// Call a fixture/test function, prepending the test class instance as
/// `self` when the definition lives inside a Test* class. Calls run in the
/// current item's contextvars context (pytest._ctx) so vars set by
/// fixtures propagate into the test.
pub fn call_fixture<'py>(
    py: Python<'py>,
    func: &Py<PyAny>,
    instance: Option<&Py<PyAny>>,
    kwargs: &[(String, Py<PyAny>)],
) -> PyResult<Bound<'py, PyAny>> {
    let dict = PyDict::new(py);
    for (name, value) in kwargs {
        dict.set_item(name, value.bind(py))?;
    }
    let call = py.import("pytest._ctx")?.getattr("call")?;
    match instance {
        Some(instance) => call.call((func.bind(py), instance.bind(py)), Some(&dict)),
        None => call.call((func.bind(py),), Some(&dict)),
    }
}

/// Begin/end the per-item contextvars context.
pub fn begin_item_context(py: Python<'_>) -> PyResult<()> {
    py.import("pytest._ctx")?.call_method0("begin_item")?;
    Ok(())
}

pub fn end_item_context(py: Python<'_>) {
    let _ = py
        .import("pytest._ctx")
        .and_then(|m| m.call_method0("end_item"));
}

/// Resume a suspended sync generator fixture, expecting StopIteration.
/// Runs in the item context so contextvar tokens reset cleanly.
pub fn finalize_generator(py: Python<'_>, generator: &Py<PyAny>) -> PyResult<()> {
    let next_fn = py.import("builtins")?.getattr("next")?;
    let call = py.import("pytest._ctx")?.getattr("call")?;
    match call.call1((next_fn, generator.bind(py))) {
        Ok(_) => Err(pyo3::exceptions::PyRuntimeError::new_err(
            "fixture generator yielded more than once",
        )),
        Err(err) if err.is_instance_of::<pyo3::exceptions::PyStopIteration>(py) => Ok(()),
        Err(err) => Err(err),
    }
}

/// Advance a generator fixture to its first yield, returning the value.
/// Runs in the item context so contextvars set before the yield propagate.
pub fn next_value<'py>(
    py: Python<'py>,
    generator: &Bound<'py, PyAny>,
) -> PyResult<Bound<'py, PyAny>> {
    let next_fn = py.import("builtins")?.getattr("next")?;
    py.import("pytest._ctx")?
        .getattr("call")?
        .call1((next_fn, generator))
}
