//! The only module allowed to touch `Python<'py>` / `Bound`.
//!
//! Engine structs store GIL-independent `Py<PyAny>` handles and re-bind
//! them here per GIL session.

use std::path::{Path, PathBuf};

use pyo3::prelude::*;
use pyo3::types::PyList;

// All embedded Python shim sources (generated by build.rs from py/):
// `pytest` is the public API shim; `_pytest` mirrors the internal module
// paths that upstream test suites import.
include!(concat!(env!("OUT_DIR"), "/shim_manifest.rs"));

mod bootstrap;
mod collecting;
mod errors;
mod fixtures;
mod proxies;
mod reporter;
mod services;

pub use bootstrap::*;
pub use collecting::*;
pub use errors::*;
pub use fixtures::*;
pub use proxies::*;
pub use reporter::*;
pub use services::*;

/// The directory holding the embedded Python shim packages.
///
/// Named after the package version and a build-time FNV-1a hash of all shim
/// file contents, so the path is stable across invocations of the same binary.
/// `install_shim` skips writing a file when it already exists at this path,
/// reducing startup from ~200+ file-writes per invocation to ~200 stat calls
/// on warm runs (order-of-magnitude faster on most OSes).
///
/// Plugin crates share the same root and apply the same skip-if-exists logic,
/// so only the first invocation after a new build pays the extraction cost.
pub fn shim_root() -> PathBuf {
    std::env::temp_dir().join(format!(
        "pytest-rs-{}-{:016x}",
        env!("CARGO_PKG_VERSION"),
        SHIM_CONTENT_HASH
    ))
}

pub fn sys_path_prepend(py: Python<'_>, path: &Path) -> PyResult<()> {
    let sys_path = py.import("sys")?.getattr("path")?;
    let sys_path = sys_path.cast::<PyList>().map_err(PyErr::from)?;
    let entry = path.to_string_lossy().to_string();
    // Remove existing occurrence first so the entry is always at position 0.
    // A simple "skip if already present" would leave the path at a lower
    // priority position when PYTHONPATH contains it after other directories,
    // allowing those earlier entries to shadow project-root packages.
    if let Some(i) = sys_path
        .iter()
        .position(|e| e.extract::<String>().ok().as_deref() == Some(&entry))
    {
        sys_path.del_item(i)?;
    }
    sys_path.insert(0, entry)?;
    Ok(())
}

/// Return the `pytest.__version__` string from the Python environment.
pub fn pytest_version(py: Python<'_>) -> PyResult<String> {
    py.import("pytest")?.getattr("__version__")?.extract()
}

/// Set an environment variable via Python's os.environ (avoids unsafe Rust
/// env mutation, and keeps Python's os.environ in sync).
pub fn setenv(py: Python<'_>, key: &str, value: &str) {
    let _ = py
        .import("os")
        .and_then(|os| os.getattr("environ"))
        .and_then(|env| env.set_item(key, value));
}

/// Remove an environment variable via Python's os.environ.
pub fn unsetenv(py: Python<'_>, key: &str) {
    let _ = py
        .import("os")
        .and_then(|os| os.getattr("environ"))
        .and_then(|env| env.call_method1("pop", (key, py.None())));
}
