//! The only module allowed to touch `Python<'py>` / `Bound`.
//!
//! Engine structs store GIL-independent `Py<PyAny>` handles and re-bind
//! them here per GIL session.

use std::path::{Path, PathBuf};

use pyo3::prelude::*;
use pyo3::types::PyList;

// All embedded Python shim sources (generated by build.rs from py/):
// `pytest` is the public API shim; `_pytest` mirrors the internal module
// paths that upstream test suites import.
include!(concat!(env!("OUT_DIR"), "/shim_manifest.rs"));

mod bootstrap;
mod collecting;
mod errors;
mod fixtures;
mod proxies;
mod reporter;
mod services;

pub use bootstrap::*;
pub use collecting::*;
pub use errors::*;
pub use fixtures::*;
pub use proxies::*;
pub use reporter::*;
pub use services::*;

/// The directory holding the embedded Python shim packages.
///
/// Named after the package version and a build-time FNV-1a hash of all shim
/// file contents, so the path is stable across invocations of the same binary.
/// `install_shim` skips writing a file already present here at full length,
/// reducing startup from ~200+ file-writes per invocation to ~200 stat calls
/// on warm runs (order-of-magnitude faster on most OSes).
///
/// Plugin crates share the same root and go through the same `write_shim_file`,
/// so only the first invocation after a new build pays the extraction cost.
pub fn shim_root() -> PathBuf {
    std::env::temp_dir().join(format!(
        "pytest-rs-{}-{:016x}",
        env!("CARGO_PKG_VERSION"),
        SHIM_CONTENT_HASH
    ))
}

/// Extract one embedded shim file to `path` unless it is already there at full
/// length, and never leave a partially written file behind.
///
/// A truncated shim file is not a harmless glitch: importing a `plugin.py`
/// missing its tail is exactly how `AttributeError: module
/// 'pytest_mock.plugin' has no attribute '_configure'` (an INTERNAL ERROR that
/// aborts the whole run before collection) happens. Two things can produce one
/// — a plain `fs::write` truncates in place, so a process that finds the path
/// present can import what another is still writing, and a run killed
/// mid-extraction leaves the stump on disk. Both matter here because the shim
/// root is shared: it is named by version + content hash, so concurrent runs
/// of the same binary write into it, a forked xdist worker configures native
/// plugins independently of its controller, and the root outlives every run
/// that reuses it.
///
/// So: rename a pid-unique sibling into place (POSIX rename within a directory
/// is atomic — the destination only ever appears complete), and gate on the
/// existing file's *length* rather than its mere existence, so a stump left by
/// an older run heals instead of being skipped forever. Length is enough: a
/// truncated write is the only corruption in play, and it always shortens the
/// file. `metadata()` costs the same as the `exists()` stat it replaces, which
/// matters for the ~200-file `install_shim` extraction on warm runs.
pub fn write_shim_file(path: &Path, content: &str) -> std::io::Result<()> {
    if std::fs::metadata(path).is_ok_and(|meta| meta.len() == content.len() as u64) {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("shim");
    // Leading dot + .tmp suffix: never importable, so a sibling orphaned by a
    // killed run cannot be picked up as a module.
    let tmp = path.with_file_name(format!(".{name}.{}.tmp", std::process::id()));
    std::fs::write(&tmp, content)?;
    std::fs::rename(&tmp, path).inspect_err(|_| {
        let _ = std::fs::remove_file(&tmp);
    })
}

/// Split a raw ini string the way upstream's `_getini` handles `type="paths"`
/// / `type="args"` values: `shlex.split(value)` on the whole string (not
/// per-line — a multi-line ini value's embedded `\n`s are just more
/// whitespace to shlex). Falls back to a plain whitespace split if `shlex`
/// itself errors (e.g. unbalanced quotes), matching Python's own behavior of
/// letting `shlex.split` raise rather than silently mangling input — but a
/// hard error here would be an odd place to surface a ValueError, so this
/// degrades gracefully instead.
pub fn shlex_split(py: Python<'_>, value: &str) -> Vec<String> {
    py.import("shlex")
        .and_then(|m| m.call_method1("split", (value,)))
        .and_then(|v| v.extract::<Vec<String>>())
        .unwrap_or_else(|_| value.split_whitespace().map(str::to_string).collect())
}

/// The `pythonpath` ini's entries resolved to absolute paths — the same
/// list both the add side (`Engine::run`/`run_nested`, prepending each to
/// `sys.path`) and the remove side (session teardown) need, so they can
/// never drift apart.
pub fn pythonpath_entries(py: Python<'_>, config: &crate::config::Config) -> Vec<PathBuf> {
    let Some(raw) = config.get_ini("pythonpath") else {
        return vec![];
    };
    let rels: Vec<String> = if raw.contains('\x00') {
        raw.split('\x00')
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .map(String::from)
            .collect()
    } else {
        shlex_split(py, raw)
    };
    rels.into_iter()
        .map(|rel| config.rootdir.join(rel))
        .collect()
}

/// Remove every `pythonpath` entry previously prepended to `sys.path`
/// (upstream's `Config._unconfigure_python_path`, run as a cleanup callback
/// at session teardown so a nested/second run starts with a clean slate and
/// doesn't just accumulate entries).
pub fn pythonpath_cleanup(py: Python<'_>, config: &crate::config::Config) {
    let sys_path = match py.import("sys").and_then(|m| m.getattr("path")) {
        Ok(p) => p,
        Err(_) => return,
    };
    let Ok(sys_path) = sys_path.cast::<PyList>() else {
        return;
    };
    for path in pythonpath_entries(py, config) {
        let entry = path.to_string_lossy().to_string();
        if let Some(i) = sys_path
            .iter()
            .position(|e| e.extract::<String>().ok().as_deref() == Some(&entry))
        {
            let _ = sys_path.del_item(i);
        }
    }
}

pub fn sys_path_prepend(py: Python<'_>, path: &Path) -> PyResult<()> {
    let sys_path = py.import("sys")?.getattr("path")?;
    let sys_path = sys_path.cast::<PyList>().map_err(PyErr::from)?;
    let entry = path.to_string_lossy().to_string();
    // Remove existing occurrence first so the entry is always at position 0.
    // A simple "skip if already present" would leave the path at a lower
    // priority position when PYTHONPATH contains it after other directories,
    // allowing those earlier entries to shadow project-root packages.
    if let Some(i) = sys_path
        .iter()
        .position(|e| e.extract::<String>().ok().as_deref() == Some(&entry))
    {
        sys_path.del_item(i)?;
    }
    sys_path.insert(0, entry)?;
    Ok(())
}

/// `--import-mode=append`: like prepend, but the directory is appended to
/// the end of `sys.path` (only if not already present), so it is searched
/// after directories already there.
pub fn sys_path_append(py: Python<'_>, path: &Path) -> PyResult<()> {
    let sys_path = py.import("sys")?.getattr("path")?;
    let sys_path = sys_path.cast::<PyList>().map_err(PyErr::from)?;
    let entry = path.to_string_lossy().to_string();
    let already_present = sys_path
        .iter()
        .any(|e| e.extract::<String>().ok().as_deref() == Some(&entry));
    if !already_present {
        sys_path.append(entry)?;
    }
    Ok(())
}

/// Return the `pytest.__version__` string from the Python environment.
pub fn pytest_version(py: Python<'_>) -> PyResult<String> {
    py.import("pytest")?.getattr("__version__")?.extract()
}

/// Set an environment variable via Python's os.environ (avoids unsafe Rust
/// env mutation, and keeps Python's os.environ in sync).
pub fn setenv(py: Python<'_>, key: &str, value: &str) {
    let _ = py
        .import("os")
        .and_then(|os| os.getattr("environ"))
        .and_then(|env| env.set_item(key, value));
}

/// Remove an environment variable via Python's os.environ.
pub fn unsetenv(py: Python<'_>, key: &str) {
    let _ = py
        .import("os")
        .and_then(|os| os.getattr("environ"))
        .and_then(|env| env.call_method1("pop", (key, py.None())));
}
